### PR TITLE
[REVIEW] remove responsive size helper

### PR DESCRIPTION
**Pull request by adamrenklint**
@iamtimm please review and release

### CODE REVIEW

**Comment by iamtimm** [comment]
I wouldn't remove the code completely but just hide it in my opinion, because we constantly use it.

**Comment by adamrenklint** [comment]
And this should be shown only on the example pages in this repo? What if we added it as a separate CSS file, that is not included in the build and distribution?

**Comment by iamtimm** [comment]
I guess that's a better way of doing it to ensure we don't forget to remove it.

**Comment by adamrenklint** [comment]
Cool, will do that tomorrow.

**Comment by iamtimm** [comment]
Thanks :+1:

**Comment by adamrenklint** [comment]
@iamtimm changed, please review again

**Pull request merged**
